apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-fe-app
  namespace: myargocd-n
spec:
  project: default
  source:
    repoURL: https://github.com/REVOgati/ArgoCD_Local_Test.git
    targetRevision: HEAD
    path: 05-Projects/app1-frontend-config/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: myns-1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true